### PR TITLE
Support google app engine

### PR DESCRIPTION
**Pull request by jonathan-s**
Google appengine's support for requests is sketchy at best. So this PR adds support for urlfetch.

### CODE REVIEW

**Comment by patrys** [comment]
Would it make sense to always use `urlfetch` if it can be imported?

**Comment by jonathan-s** [comment]
It would actually.

**Comment by patrys** [comment]
How about define `_request` in `except` and `else` clauses of the `try/import`?

**Comment by jonathan-s** [comment]
I took a look at how the [try/except/else](http://stackoverflow.com/questions/855759/python-try-else) worked but I can't really see how it would be useful in this case. 

    try:
        from google.appengine.api import urlfetch
        USE_URLFETCH = True
    except ImportError:
        USE_URLFETCH = False

And then check whether value is true or false to determine if we can execute urlfetch.

**Comment by jonathan-s** [comment]
Perhaps you thought about doing something like this:
    
    def _request(data, extra_headers):
        try:
            return urlfetch.fetch(url=TRACKING_URI, payload=data, method=urlfetch.POST,
                                  headers=extra_headers)
        except NameError:
            return requests.post(TRACKING_URI, data=data, headers=extra_headers,
                                 timeout=5.0)

Seems preferable to the former suggestion I had. So let's go for that one?

**Comment by patrys** [comment]
I was thinking something like:

```python
try:
    from google.appengine.api import urlfetch
except ImportError:
    def _request(data, extra_headers):
        return requests.post(TRACKING_URI, data=data, headers=extra_headers,
                             timeout=5.0)
else:
    def _request(data, extra_headers):
        return urlfetch.fetch(url=TRACKING_URI, payload=data, method=urlfetch.POST,
                              headers=extra_headers)
```

**Comment by jonathan-s** [comment]
Thanks for telling me. Though personally I find it less readable than the latest commit. But if you prefer it that way I'll make another commit that reflects that :)

**Comment by patrys** [comment]
It is a bit less readable but it only determines the method to use once.

By the way, there is also sigmavirus24/requests-toolbelt#114 so in the long run this may become obsolete.

**Pull request closed without merging**
